import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/hooks/userContext";

export const metadata: Metadata = {
  title: "Asia University",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className="font-satoshi">{children}</body>
      </UserProvider>
    </html>
  );
}
